apiVersion: apps/v1
kind: Deployment
metadata:
  name: aeron-publisher
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher
          image: aeron-publisher:1.0
          ports:
            - containerPort: 80